# -*- coding: utf-8 -*-
"""Hand-written texts for the Quran words trainer: explanations of the
prefixes / pronoun endings (shown ONCE, the first time a learner meets them)
and surah names in Russian and Uzbek. Tajik surah names come from the
SakinaDevGroup metadata; English from Quran.com (see merge_meanings.py).

In Uzbek strings "^" stands for the letter ʻ (U+02BB: oʻ, gʻ) and "~" for
the tutuq belgisi ʼ (U+02BC); merge_meanings.py converts them.
"""

# key (as in public/quran/lexicon.json "affixes", joined with ":") ->
#   (ru, tj, uz, en)
AFFIXES = {
    "PRE:P:ب": ("би- — «в, с, посредством» (предлог)", "би- — «бо, дар, ба воситаи» (пешоянд)",
                "bi- — «bilan, -da, orqali» (old ko^makchi)", "bi- — 'in, with, by' (preposition)"),
    "PRE:DET:ال": ("аль- — определённый артикль (тот самый, известный)", "ал- — ҳарфи таъриф (муайянкунанда)",
                   "al- — aniqlik artikli (ma~lum narsa)", "al- — definite article 'the'"),
    "PRE:P:ل": ("ли- — «для, к, у» (предлог)", "ли- — «барои, ба» (пешоянд)",
                "li- — «uchun, -ga» (old ko^makchi)", "li- — 'for, to' (preposition)"),
    "PRE:CONJ:و": ("ва- — «и» (союз)", "ва- — «ва» (пайвандак)",
                   "va- — «va» (bog^lovchi)", "wa- — 'and' (conjunction)"),
    "PRE:REM:و": ("ва- — «и» (начало новой мысли)", "ва- — «ва» (оғози фикри нав)",
                  "va- — «va» (yangi fikr boshi)", "wa- — 'and' (starts a new sentence)"),
    "PRE:CIRC:و": ("ва- — «в то время как, при этом»", "ва- — «ҳол он ки, дар ҳоле ки»",
                   "va- — «holbuki, ...ganda» (hol)", "wa- — 'while' (circumstance)"),
    "PRE:SUP:و": ("ва- — связующая частица", "ва- — ҳарфи пайвасткунанда",
                  "va- — bog^lovchi yuklama", "wa- — linking particle"),
    "PRE:COM:و": ("ва- — «вместе с»", "ва- — «бо, ҳамроҳи»",
                  "va- — «bilan birga»", "wa- — 'together with'"),
    "PRE:P:و": ("ва- — «клянусь…» (клятва)", "ва- — «қасам ба…» (қасам)",
                "va- — «qasamki…» (qasam)", "wa- — 'by…' (oath)"),
    "PRE:P:ت": ("та- — «клянусь…» (клятва: таллахи)", "та- — «қасам ба…» (таллоҳи)",
                "ta- — «qasamki…» (tallohi)", "ta- — 'by…' (oath: tallāhi)"),
    "PRE:P:ك": ("ка- — «как, подобно»", "ка- — «мисли, монанди»",
                "ka- — «kabi, singari»", "ka- — 'like, as'"),
    "PRE:CONJ:ف": ("фа- — «и, и затем» (союз)", "фа- — «пас, баъд» (пайвандак)",
                   "fa- — «va, so^ng» (bog^lovchi)", "fa- — 'and, then' (conjunction)"),
    "PRE:REM:ف": ("фа- — «и вот, итак»", "фа- — «пас, инак»",
                  "fa- — «bas, mana»", "fa- — 'so, then' (resumption)"),
    "PRE:RSLT:ف": ("фа- — «то, тогда» (следствие)", "фа- — «пас, он гоҳ» (натиҷа)",
                   "fa- — «unda, u holda» (natija)", "fa- — 'then' (result)"),
    "PRE:CAUS:ف": ("фа- — «чтобы, ведь» (причина)", "фа- — «то ки, зеро» (сабаб)",
                   "fa- — «toki, chunki» (sabab)", "fa- — 'so that' (cause)"),
    "PRE:SUP:ف": ("фа- — связующая частица", "фа- — ҳарфи пайвасткунанда",
                  "fa- — bog^lovchi yuklama", "fa- — linking particle"),
    "PRE:INTG:أ": ("а- — вопрос («разве?», «ли?»)", "а- — савол («оё?»)",
                   "a- — so^roq («...mi?»)", "a- — question ('is it?', 'do?')"),
    "PRE:EQ:أ": ("а- — «ли… или» (всё равно)", "а- — «оё… ё» (баробарӣ)",
                 "a- — «...mi yoki ...mi» (tenglik)", "a- — 'whether… or'"),
    "PRE:EMPH:ل": ("ла- — «непременно, поистине» (усиление)", "ла- — «албатта, ҳатман» (таъкид)",
                   "la- — «albatta, shubhasiz» (ta~kid)", "la- — 'surely, indeed' (emphasis)"),
    "PRE:PRP:ل": ("ли- — «чтобы» (цель)", "ли- — «то ки» (мақсад)",
                  "li- — «uchun, toki» (maqsad)", "li- — 'so that' (purpose)"),
    "PRE:IMPV:ل": ("ли- — «пусть» (повеление)", "ли- — «бигзор» (амр)",
                   "li- — «-sin» (buyruq)", "li- — 'let' (command)"),
    "PRE:VOC:ي": ("йа- — «о!» (обращение)", "ё- — «эй!» (нидо)",
                  "yā- — «ey!» (undov)", "yā- — 'O!' (calling)"),
    "PRE:ATT:ه": ("ха- — «вот» (привлекает внимание)", "ҳо- — «инак» (ҷалби диққат)",
                  "hā- — «mana» (diqqat)", "hā- — 'here!' (attention)"),
    "PRE:FUT:س": ("са- — «будет» (будущее время)", "са- — «хоҳад» (замони оянда)",
                  "sa- — kelasi zamon («-adi»)", "sa- — 'will' (future)"),
    "SUF:1S": ("-и / -ни — «я, меня, мой»", "-ӣ / -нӣ — «ман, маро, аз ман»",
               "-ī / -nī — «men, meni, mening»", "-ī / -nī — 'I, me, my'"),
    "SUF:1P": ("-на — «мы, нас, наш»", "-но — «мо, моро, аз мо»",
               "-nā — «biz, bizni, bizning»", "-nā — 'we, us, our'"),
    "SUF:2MS": ("-ка — «ты, тебя, твой» (м.р.)", "-ка — «ту, туро, аз ту» (мард)",
                "-ka — «sen, seni, sening» (erkak)", "-ka — 'you, your' (m. sg.)"),
    "SUF:2FS": ("-ки — «ты, тебя, твой» (ж.р.)", "-ки — «ту, туро, аз ту» (зан)",
                "-ki — «sen, seni, sening» (ayol)", "-ki — 'you, your' (f. sg.)"),
    "SUF:2D": ("-кума — «вы двое, вас двоих»", "-кумо — «шумо ду»",
               "-kumā — «siz ikkingiz»", "-kumā — 'you two'"),
    "SUF:2MP": ("-кум / -тум — «вы, вас, ваш»", "-кум / -тум — «шумо, шуморо, аз шумо»",
                "-kum / -tum — «sizlar, sizni, sizning»", "-kum / -tum — 'you, your' (pl.)"),
    "SUF:2FP": ("-кунна — «вы, вас» (ж.р.)", "-кунна — «шумо» (занон)",
                "-kunna — «sizlar» (ayollar)", "-kunna — 'you' (f. pl.)"),
    "SUF:3MS": ("-ху — «он, его»", "-ҳу — «ӯ, ӯро, аз ӯ»",
                "-hu — «u, uni, uning»", "-hu — 'he, him, his, it'"),
    "SUF:3FS": ("-ха — «она, её»", "-ҳо — «ӯ, ӯро, аз ӯ» (зан)",
                "-hā — «u, uni, uning» (ayol)", "-hā — 'she, her, it'"),
    "SUF:3D": ("-хума — «они двое, их двоих»", "-ҳумо — «он ду»",
               "-humā — «ular ikkisi»", "-humā — 'they two, both of them'"),
    "SUF:3MD": ("-хума / -а — «они двое» (м.р.)", "-ҳумо / -о — «он ду» (мард)",
                "-humā / -ā — «ular ikkisi» (erkak)", "-humā / -ā — 'they two' (m.)"),
    "SUF:3FD": ("-хума / -та — «они двое» (ж.р.)", "-ҳумо / -то — «он ду» (зан)",
                "-humā / -tā — «ular ikkisi» (ayol)", "-humā / -tā — 'they two' (f.)"),
    "SUF:3MP": ("-хум / -у(на) — «они, их»", "-ҳум / -у(на) — «онҳо, онҳоро»",
                "-hum / -ū(na) — «ular, ularni, ularning»", "-hum / -ū(na) — 'they, them, their'"),
    "SUF:3FP": ("-хунна / -на — «они, их» (ж.р.)", "-ҳунна / -на — «онҳо» (занон)",
                "-hunna / -na — «ular» (ayollar)", "-hunna / -na — 'they, them' (f. pl.)"),
}

SURAH_RU = [
    "Аль-Фатиха", "Аль-Бакара", "Аль Имран", "Ан-Ниса", "Аль-Маида", "Аль-Анам", "Аль-Араф", "Аль-Анфаль",
    "Ат-Тауба", "Юнус", "Худ", "Юсуф", "Ар-Рад", "Ибрахим", "Аль-Хиджр", "Ан-Нахль", "Аль-Исра", "Аль-Кахф",
    "Марьям", "Та Ха", "Аль-Анбия", "Аль-Хадж", "Аль-Муминун", "Ан-Нур", "Аль-Фуркан", "Аш-Шуара", "Ан-Намль",
    "Аль-Касас", "Аль-Анкабут", "Ар-Рум", "Лукман", "Ас-Саджда", "Аль-Ахзаб", "Саба", "Фатыр", "Йа Син",
    "Ас-Саффат", "Сад", "Аз-Зумар", "Гафир", "Фуссылат", "Аш-Шура", "Аз-Зухруф", "Ад-Духан", "Аль-Джасия",
    "Аль-Ахкаф", "Мухаммад", "Аль-Фатх", "Аль-Худжурат", "Каф", "Аз-Зарият", "Ат-Тур", "Ан-Наджм", "Аль-Камар",
    "Ар-Рахман", "Аль-Вакиа", "Аль-Хадид", "Аль-Муджадила", "Аль-Хашр", "Аль-Мумтахана", "Ас-Сафф",
    "Аль-Джумуа", "Аль-Мунафикун", "Ат-Тагабун", "Ат-Талак", "Ат-Тахрим", "Аль-Мульк", "Аль-Калам",
    "Аль-Хакка", "Аль-Мааридж", "Нух", "Аль-Джинн", "Аль-Муззаммиль", "Аль-Муддассир", "Аль-Кияма",
    "Аль-Инсан", "Аль-Мурсалят", "Ан-Наба", "Ан-Назиат", "Абаса", "Ат-Таквир", "Аль-Инфитар",
    "Аль-Мутаффифин", "Аль-Иншикак", "Аль-Бурудж", "Ат-Тарик", "Аль-Аля", "Аль-Гашия", "Аль-Фаджр",
    "Аль-Балад", "Аш-Шамс", "Аль-Лайль", "Ад-Духа", "Аш-Шарх", "Ат-Тин", "Аль-Алак", "Аль-Кадр",
    "Аль-Баййина", "Аз-Зальзаля", "Аль-Адият", "Аль-Кариа", "Ат-Такасур", "Аль-Аср", "Аль-Хумаза",
    "Аль-Филь", "Курайш", "Аль-Маун", "Аль-Каусар", "Аль-Кафирун", "Ан-Наср", "Аль-Масад", "Аль-Ихлас",
    "Аль-Фаляк", "Ан-Нас",
]

SURAH_UZ = [
    "Fotiha", "Baqara", "Oli Imron", "Niso", "Moida", "An~om", "A~rof", "Anfol", "Tavba", "Yunus", "Hud",
    "Yusuf", "Ra~d", "Ibrohim", "Hijr", "Nahl", "Isro", "Kahf", "Maryam", "Toha", "Anbiyo", "Haj",
    "Mo^minun", "Nur", "Furqon", "Shuaro", "Naml", "Qasas", "Ankabut", "Rum", "Luqmon", "Sajda", "Ahzob",
    "Saba", "Fotir", "Yosin", "Soffot", "Sod", "Zumar", "G^ofir", "Fussilat", "Shuro", "Zuxruf", "Duxon",
    "Josiya", "Ahqof", "Muhammad", "Fath", "Hujurot", "Qof", "Zoriyot", "Tur", "Najm", "Qamar", "Rahmon",
    "Voqea", "Hadid", "Mujodala", "Hashr", "Mumtahana", "Saff", "Jum~a", "Munofiqun", "Tag^obun", "Taloq",
    "Tahrim", "Mulk", "Qalam", "Hoqqa", "Maorij", "Nuh", "Jin", "Muzzammil", "Muddassir", "Qiyomat",
    "Inson", "Mursalot", "Naba", "Noziot", "Abasa", "Takvir", "Infitor", "Mutoffifin", "Inshiqoq", "Buruj",
    "Toriq", "A~lo", "G^oshiya", "Fajr", "Balad", "Shams", "Layl", "Zuho", "Sharh", "Tin", "Alaq", "Qadr",
    "Bayyina", "Zalzala", "Odiyot", "Qori~a", "Takosur", "Asr", "Humaza", "Fil", "Quraysh", "Mo^un",
    "Kavsar", "Kofirun", "Nasr", "Masad", "Ixlos", "Falaq", "Nos",
]

# Section / UI strings used by the trainer are in the React screens (L()).
